// svelte-app/src/routes/event/[id]/reserve/my-reservations.svelte
<script lang="ts">
	import { apiFunctions } from '$lib/api';
	import Loading from '$lib/components/loading.svelte';
	import ReservationsTable from '$lib/components/reservations-table.svelte';
	import { getAuthContext } from '$lib/stores/auth-state.svelte';

	const { eventId }: { eventId: string } = $props();

	const auth = getAuthContext();

	const reservations = auth.getAccessToken().then((token) => {
		if (!token) return [];
		return apiFunctions
			.getReservationsForSelf(token, { event: eventId })
			.then((res) => res.sort((a, b) => b.startDateTime.valueOf() - a.startDateTime.valueOf()));
	});
</script>

{#await reservations}
	<Loading />
{:then reservations}
	<ReservationsTable {reservations} />
{/await}

// next-app/src/app/event/[id]/my-reservations.tsx
'use client';

import { apiFunctions } from '@/api';
import { ReservationsTable } from '@/components/reservations-table';
import { Event } from '@/interfaces/event.interface';
import { Reservation } from '@/interfaces/reservation.interface';
import { useAuthState } from '@/state/auth-state';
import { useEffect, useState } from 'react';

interface MyReservationsProps {
  event: Event;
}

export function MyReservations({ event }: MyReservationsProps) {
  const [reservations, setReservations] = useState<Reservation[]>();
  const getAccessToken = useAuthState((state) => state.getAccessToken);

  useEffect(() => {
    getAccessToken().then((token) => {
      if (!token) return;
      apiFunctions
        .getReservationsForSelf(token, { event: event._id })
        .then((res) => {
          setReservations(
            res.data.sort((a, b) => b.forDate.valueOf() - a.forDate.valueOf()),
          );
        })
        .catch((e) => {
          console.log(e);
        });
    });
  }, [event._id, getAccessToken]);

  return <ReservationsTable reservations={reservations || []} />;
}
