// svelte-app/src/lib/components/reset-password-alert.svelte
<script lang="ts">
	import { Fa } from 'svelte-fa';
	import { faWarning } from '@fortawesome/free-solid-svg-icons';
	import { getAuthContext } from '$lib/stores/auth-state.svelte';

	const { class: className = '' }: { class?: string } = $props();

	const auth = getAuthContext();
</script>

{#if auth.user?.passwordResetRequired === true}
	<div class="alert alert-warning {className}">
		<Fa icon={faWarning} class="shrink-0 h-6 w-6" />
		<span>Opozorilo: Prosim, zamenjaj geslo!</span>
		<a href="/profile/edit" class="btn btn-sm btn-outline">Zamenjaj zdaj</a>
	</div>
{/if}

// next-app/src/components/reset_password_alert.tsx
'use client';

import { useUserState } from '@/state/user-state';
import { faWarning } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Link from 'next/link';
import { useEffect } from 'react';

export function ResetPasswordAlert() {
  const [user, getUser] = useUserState((s) => [s.user, s.getUser]);

  useEffect(() => {
    getUser();
  }, [getUser]);

  if (user?.passwordResetRequired !== true) {
    return null;
  }

  return (
    <div className="alert alert-warning">
      <FontAwesomeIcon
        icon={faWarning}
        width={24}
        height={24}
        className="shrink-0"
      />
      <span>Opozorilo: Prosim zamenjaj geslo!</span>
      <Link href="/profile/edit" className="btn btn-sm">
        Zamenjaj zdaj
      </Link>
    </div>
  );
}
