// next-app/src/app/event/[id]/free-dates-component.tsx
'use client';
import { apiFunctions } from '@/api';
import { Event } from '@/interfaces/event.interface';
import { Reservation } from '@/interfaces/reservation.interface';
import { dayInMs, hourInMs } from '@/util/date.util';
import { useEffect, useState } from 'react';
import { Band } from '@/enums/band.enum';
import { Mode } from '@/enums/mode.enum';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faChevronLeft,
  faChevronRight,
} from '@fortawesome/free-solid-svg-icons';

export function FreeDatesComponent({ event }: { event: Event }) {
  const [reservations, setReservations] = useState<Reservation[]>();

  const [date, setDate] = useState<string>(
    new Date().toISOString().slice(0, 10),
  );
  const [mode, setMode] = useState<Mode>();

  const bands = Object.values(Band).map((val) => val.toString());

  useEffect(() => {
    setReservations(undefined);
    apiFunctions
      .getReservationsForEvent(event._id, {
        start: date,
        end: new Date(new Date(date).valueOf() + dayInMs).toISOString(),
      })
      .then(setReservations)
      .catch(console.error);
  }, [event._id, date]);

  const freeTable = bands.map(() =>
    new Array<Set<string> | null>(24)
      .fill(null)
      .map(() => (reservations == undefined ? null : new Set<string>())),
  );

  const dateV = new Date(date).valueOf() / hourInMs;
  if (reservations) {
    for (const reservation of reservations) {
      if (mode && !reservation.modes.includes(mode)) continue;

      const start = Math.max(
        Math.floor(reservation.startDateTime.valueOf() / hourInMs),
        dateV,
      );
      const end = Math.min(
        Math.ceil(reservation.endDateTime.valueOf() / hourInMs),
        dateV + 24,
      );

      for (let i = start; i < end; ++i) {
        const timeI = i - dateV;
        if (timeI < 0 || timeI > 23) {
          console.error('Invalid hour', i);
          continue;
        }
        for (const band of reservation.bands) {
          if (!bands.includes(band)) continue;
          for (const mode of reservation.modes) {
            freeTable[bands.indexOf(band)][timeI]?.add(mode);
          }
        }
      }
    }
  }

  return (
    <div className="flex flex-col gap-5 md:flex-row">
      <div className="flex flex-1 flex-col justify-start gap-3 px-6 py-2 md:border-r">
        <h3 className="label border-b text-xl font-bold">Filtri</h3>

        <div className="form-control">
          <label className="label">
            <span className="label-text">Datum</span>
          </label>
          <input
            type="date"
            className="input input-bordered"
            value={date}
            min={event.fromDateTime?.toISOString().slice(0, 10)}
            max={event.toDateTime?.toISOString().slice(0, 10)}
            onChange={(e) => {
              const val = e.target.value;
              if (!val) return;
              setDate(val);
            }}
          />
          <div className="mt-2 flex gap-2">
            <button
              className="btn btn-primary btn-sm flex-1"
              onClick={() => {
                const d = new Date(date);
                d.setDate(d.getDate() - 1);
                setDate(d.toISOString().slice(0, 10));
              }}
            >
              <FontAwesomeIcon icon={faChevronLeft} />
            </button>
            <button
              className="btn btn-primary btn-sm flex-1"
              onClick={() => {
                const d = new Date(date);
                d.setDate(d.getDate() + 1);
                setDate(d.toISOString().slice(0, 10));
              }}
            >
              <FontAwesomeIcon icon={faChevronRight} />
            </button>
          </div>
        </div>
        <div className="form-control">
          <label className="label">
            <span className="label-text">Način</span>
          </label>
          <select
            className="select select-bordered w-full"
            value={mode?.toString() ?? ''}
            onChange={(e) => {
              const val = e.target.value;
              if (val == '') setMode(undefined);
              else setMode(val as Mode);
            }}
          >
            <option value="">Vsi</option>
            {Object.values(Mode).map((band) => (
              <option key={band}>{band}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="flex-[2] overflow-x-auto">
        <table className="table mx-auto w-auto">
          <tbody>
            <tr>
              <td />
              <td>
                <div className="flex">
                  <div className="w-12 border-l border-base-300 pl-0.5">0</div>
                  <div className="w-12 border-l border-base-300 pl-0.5">4</div>
                  <div className="w-12 border-l border-base-300 pl-0.5">8</div>
                  <div className="w-12 border-l border-base-300 pl-0.5">12</div>
                  <div className="w-12 border-l border-base-300 pl-0.5">16</div>
                  <div className="w-12 border-l border-base-300 pl-0.5">20</div>
                </div>
              </td>
            </tr>

            {Object.values(Band).map((band, bi) => (
              <tr key={band}>
                <th key={band} className="px-3 py-2">
                  {band}
                </th>
                <td>
                  <div className="flex">
                    {freeTable[bi].map((taken, i) => (
                      <div
                        key={i}
                        className={`m-auto h-3 w-3 border-l border-base-200 first:rounded-l-full first:border-0 last:rounded-r-full ${
                          taken?.size ?? 0 ? 'tooltip' : ''
                        } ${
                          taken == null
                            ? 'bg-base-200'
                            : taken.size == 0
                            ? 'bg-green-500/90'
                            : 'bg-red-500/90'
                        }`}
                        data-tip={`Zasedeni načini: ${Array.from(
                          taken?.values() ?? [],
                        ).join(', ')}`}
                      />
                    ))}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// svelte-app/src/routes/event/[id]/free-dates-component.svelte
<script lang="ts">
	import type { Event } from '$lib/interfaces/event.interface';
	import { Band, COMMON_BANDS } from '$lib/enums/band.enum';
	import { COMMON_MODES, Mode } from '$lib/enums/mode.enum';
	import Fa from 'svelte-fa';
	import { faChevronLeft, faChevronRight } from '@fortawesome/free-solid-svg-icons';
	import type { Reservation } from '$lib/interfaces/reservation.interface';
	import { apiFunctions } from '$lib/api';
	import { dayInMs } from '$lib/util/date.util';
	import { mapReservations } from '.';

	const { event }: { event: Event } = $props();

	let reservations = $state<Reservation[]>();

	let date = $state(new Date().toISOString().slice(0, 10));
	let band = $state<Band>();
	let mode = $state<Mode>();

	const bands = $derived(band ? [band.toString()] : COMMON_BANDS.map((band) => band.toString()));
	const modes = $derived(
		mode ? [mode.toString()] : Object.values(Mode).map((mode) => mode.toString())
	);

	const freeTable = $derived(mapReservations(reservations, bands, modes, new Date(date)));

	$effect(() => {
		reservations = undefined;
		apiFunctions
			.getReservationsForEvent(event._id, {
				start: date,
				end: new Date(new Date(date).valueOf() + dayInMs).toISOString()
			})
			.then((r) => (reservations = r))
			.catch(console.error);
	});

	const formatTime = (hour: number) => `${hour.toString().padStart(2, '0')}:00`;
</script>

<div class="flex flex-col gap-5 md:flex-row">
	<div class="flex flex-1 flex-col justify-start gap-3 px-6 py-4 border rounded-xl">
		<div class="flex justify-between items-center">
			<h3 class="text-xl font-semibold">Filtri</h3>
			<button
				class="btn btn-sm btn-primary btn-outline"
				onclick={() => {
					band = undefined;
					mode = undefined;
				}}>Počisti</button
			>
		</div>

		<label class="form-control">
			<div class="label">
				<span class="label-text">Datum</span>
			</div>
			<input
				type="date"
				class="input input-bordered"
				bind:value={date}
				min={event.fromDateTime?.toISOString().slice(0, 10)}
				max={event.toDateTime?.toISOString().slice(0, 10)}
			/>
			<div class="mt-2 flex gap-2">
				<button
					class="btn btn-primary btn-sm flex-1"
					onclick={() => {
						const d = new Date(date);
						d.setDate(d.getDate() - 1);
						date = d.toISOString().slice(0, 10);
					}}
				>
					<Fa icon={faChevronLeft} />
				</button>
				<button
					class="btn btn-primary btn-sm flex-1"
					onclick={() => {
						const d = new Date(date);
						d.setDate(d.getDate() + 1);
						date = d.toISOString().slice(0, 10);
					}}
				>
					<Fa icon={faChevronRight} />
				</button>
			</div>
		</label>
		<div class="form-control">
			<div class="label">
				<span class="label-text">Frekvenčni pas</span>
			</div>
			<div class="grid grid-cols-[repeat(auto-fill,minmax(60px,1fr))] gap-1">
				{#each COMMON_BANDS as b}
					<button
						class={`btn btn-sm ${band === b ? 'btn-primary' : ''}`}
						onclick={() => {
							if (band === b) band = undefined;
							else band = b;
						}}
					>
						{b}
					</button>
				{/each}
			</div>
			<select
				class="select select-bordered select-xs mt-2 w-full"
				value={band?.toString() ?? ''}
				onchange={(e) => {
					const val = e.currentTarget.value;
					if (val == '') band = undefined;
					else band = val as Band;
				}}
			>
				<option value="">---</option>
				{#each Object.values(Band) as band}
					<option value={band}>{band}</option>
				{/each}
			</select>
			<!-- <label class="label">
          <span class="label-text-alt">
            Tukaj se nahajajo vsi frekvenčni pasovi
          </span>
        </label> -->
		</div>
		<div class="form-control">
			<div class="label">
				<span class="label-text">Način</span>
			</div>
			<div class="grid grid-cols-[repeat(auto-fill,minmax(60px,1fr))] gap-1">
				{#each COMMON_MODES as m}
					<button
						class={`btn btn-sm ${mode === m ? 'btn-primary' : ''}`}
						onclick={() => {
							mode = mode === m ? undefined : m;
						}}
					>
						{m}
					</button>
				{/each}
			</div>
			<select
				class="select select-bordered w-full mt-2"
				value={mode?.toString() ?? ''}
				onchange={(e) => {
					const val = e.currentTarget.value;
					if (val == '') mode = undefined;
					else mode = val as Mode;
				}}
			>
				<option value="">Vsi</option>
				{#each Object.values(Mode) as mode}
					<option value={mode}>{mode}</option>
				{/each}
			</select>
		</div>
	</div>

	<div class="flex-[2]">
		<table class="table mx-auto w-auto">
			<tbody>
				<tr>
					<td></td>
					<td>
						<div class="flex">
							<div class="w-12 border-l border-base-300 pl-1">0</div>
							<div class="w-12 border-l border-base-300 pl-1">4</div>
							<div class="w-12 border-l border-base-300 pl-1">8</div>
							<div class="w-12 border-l border-base-300 pl-1">12</div>
							<div class="w-12 border-l border-base-300 pl-1">16</div>
							<div class="w-12 border-l border-base-300 pl-1">20</div>
						</div>
					</td>
				</tr>

				{#each bands as band, bi}
					<tr>
						<th class="px-3 py-2">
							{band}
						</th>
						<td>
							<div class="flex">
								{#each freeTable[bi] as taken, i}
									<div
										class={`tooltip m-auto h-3 w-3 border-l border-base-200 first:rounded-l-full first:border-0 last:rounded-r-full ${
											taken == null
												? 'bg-base-200'
												: taken.size == 0
													? 'bg-success/80'
													: mode || taken.size == Object.values(Mode).length
														? 'bg-error/70'
														: 'bg-warning/90'
										}`}
										data-tip={`${formatTime(i)} - ${formatTime(i + 1)} UTC`}
									></div>
								{/each}
							</div>
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</div>
