// next-app/src/components/current-events.tsx
'use client';

import { apiFunctions } from '@/api';
import { Event } from '@/interfaces/event.interface';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { EventCard } from './event-card';

export function CurrentEvents() {
  const [events, setEvents] = useState<Event[]>();

  useEffect(() => {
    apiFunctions.getCurrentEvents().then((res) => setEvents(res.data));
  }, []);

  return (
    <div className="flex flex-col gap-2">
      <h2 className="text-2xl">Trenutni dogodki</h2>

      {(events?.length ?? 0) === 0 ? (
        <p className="opacity-90">Yoooo, no events, come back another day</p>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {events?.map((event, i) => (
            <Link key={i} href={`/event/${event._id}`}>
              <EventCard event={event} />
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}

// svelte-app/src/lib/components/current-events.svelte
<script lang="ts">
	import { apiFunctions } from '$lib/api';
	import type { Event } from '$lib/interfaces/event.interface';
	import { onMount } from 'svelte';
	import EventCard from './event-card.svelte';
	import Loading from './loading.svelte';

	let events = $state<Event[]>();

	onMount(async () => {
		apiFunctions.getCurrentEvents().then((res) => {
			events = res;
		});
	});
</script>

<div class="flex flex-col gap-2">
	<h2 class="text-2xl">Trenutni dogodki</h2>

	{#if events === undefined}
		<Loading />
	{:else if events.length === 0}
		<p class="opacity-90">No events</p>
	{:else}
		<div class="grid gap-4 sm:grid-cols-[repeat(auto-fill,minmax(350px,1fr))]">
			{#each events as event}
				<a href="/event/{event._id}">
					<EventCard {event} />
				</a>
			{/each}
		</div>
	{/if}
</div>
